Use `uniq` when finding root device in grub activation script
If the system is using mdraid on the root disk, the `lsblk` invocation
will return two lines matching "/$", e.g.:

/dev/md1
/dev/md1

This then breaks the subsequent `blkid` invocations, so $root_uuid and
$root_type are set to empty strings.  When you later boot into the
migration system, grub gives two errors:

error: one argument expected.
error: no such device: root.

Adding `uniq` fixes this.